; Compact Damage Numbers for Genshin Impact

namespace = CompactDamageGI

[Constants]
global $enable = 1

[KeyToggleCompactDamage]
key = no_modifiers END
type = cycle
$enable = 0,1

; ---------------------------------------------------------------------------

[ShaderOverrideDamageText]
hash = cf73c94cd003da41
allow_duplicate_hash = true

if $enable
  x220 = instance_count
  run = CustomShaderDamageText
endif

[CustomShaderDamageText]
vs = .\shaders\DamageText-cf73c94cd003da41-vs.hlsl
ps = .\shaders\DamageText-327cc44412c2049e-ps.hlsl
ps-t110 = ResourceSuffixGlyphs
; The vertex shader reads the font atlas to tell the digits apart.
vs-t100 = ps-t0
handling = skip
draw = from_caller

[ResourceSuffixGlyphs]
filename = .\textures\SuffixGlyphs.dds

; ---------------------------------------------------------------------------

[ShaderOverrideDamageTextSpecial]
hash = 1805540bc5f33df8
allow_duplicate_hash = true

if $enable
  x220 = instance_count
  run = CustomShaderDamageTextSpecial
endif

[CustomShaderDamageTextSpecial]
vs = .\shaders\DamageText-1805540bc5f33df8-vs.hlsl
ps = .\shaders\DamageText-aae5825e1f29c64a-ps.hlsl
ps-t110 = ResourceSuffixGlyphs
; The vertex shader reads the font atlas to tell the digits apart.
vs-t100 = ps-t2
handling = skip
draw = from_caller
