// Only change from the game's shader: alpha from SuffixGlyphs when TEXCOORD1.z is set.

// Font atlas (alpha only).
Texture2D<float4> t0 : register(t0);

SamplerState s0_s : register(s0);

Texture2D<float4> SuffixGlyphs : register(t110);

// 3Dmigoto declarations
#define cmp -
Texture1D<float4> IniParams : register(t120);

void main(
    float2 v0 : TEXCOORD0,
    float4 v1 : SV_POSITION0,
    float4 v2 : COLOR0,
    float4 v3 : TEXCOORD1,
    uint v4 : SV_InstanceID0,
    out float4 o0 : SV_Target0)
{
    float4 r0;
    uint4 bitmask, uiDest;
    float4 fDest;

    bool is_suffix = v3.z > 0.5;

    // r0.x = t0.Sample(s0_s, v0.xy).w;
    r0.x = is_suffix ? SuffixGlyphs.Sample(s0_s, v0.xy).w : t0.Sample(s0_s, v0.xy).w;
    o0.w = v2.w * r0.x;
    o0.xyz = v2.xyz;
    return;
}

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Mon Sep 21 12:27:14 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy
// SV_POSITION              0   xyzw        1      POS   float
// COLOR                    0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float
// SV_InstanceID            0   x           4     NONE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v0.xy
dcl_input_ps linear v2.xyzw
dcl_output o0.xyzw
dcl_temps 1
sample_indexable(texture2d)(float,float,float,float) r0.x, v0.xyxx, t0.wxyz, s0
mul o0.w, r0.x, v2.w
mov o0.xyz, v2.xyzx
ret
// Approximately 0 instruction slots used

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
