// Changes from the game's shader: alpha from SuffixGlyphs when TEXCOORD1.w is set, and gradient v clamped.
// Suffixes keep the game's gradient (same colors as the digits).

// Font atlas.
Texture2D<float4> t2 : register(t2);

// Outline gradient.
Texture2D<float4> t1 : register(t1);

// Fill gradient.
Texture2D<float4> t0 : register(t0);

SamplerState s2_s : register(s2);

SamplerState s1_s : register(s1);

SamplerState s0_s : register(s0);

Texture2D<float4> SuffixGlyphs : register(t110);

// 3Dmigoto declarations
#define cmp -
Texture1D<float4> IniParams : register(t120);

void main(
    float2 v0 : TEXCOORD0,
    float4 v1 : SV_POSITION0,
    float4 v2 : COLOR0,
    float4 v3 : TEXCOORD1,
    uint v4 : SV_InstanceID0,
    out float4 o0 : SV_Target0)
{
    float4 r0,r1;
    uint4 bitmask, uiDest;
    float4 fDest;

    // Clamp v: suffix quads are taller than the digit box.
    float2 gradient_uv = float2(v3.x, saturate(v3.y));
    bool is_suffix = v3.w > 0.5;

    // r0.xyzw = t1.Sample(s2_s, v3.xy).xyzw;
    // r1.xyzw = t0.Sample(s1_s, v3.xy).xyzw;
    r0.xyzw = t1.Sample(s2_s, gradient_uv).xyzw;
    r1.xyzw = t0.Sample(s1_s, gradient_uv).xyzw;
    r0.xyzw = -r1.xyzw + r0.xyzw;
    r0.xyzw = v3.zzzz * r0.xyzw + r1.xyzw;
    r0.xyzw = v2.xyzw * r0.xyzw;
    // r1.x = t2.Sample(s0_s, v0.xy).w;
    r1.x = is_suffix ? SuffixGlyphs.Sample(s0_s, v0.xy).w : t2.Sample(s0_s, v0.xy).w;
    o0.w = r1.x * r0.w;
    o0.xyz = r0.xyz;
    return;
}

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Mon Sep 21 12:26:32 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy
// SV_POSITION              0   xyzw        1      POS   float
// COLOR                    0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyz
// SV_InstanceID            0   x           4     NONE    uint
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps linear v0.xy
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xyz
dcl_output o0.xyzw
dcl_temps 2
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v3.xyxx, t1.xyzw, s2
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, v3.xyxx, t0.xyzw, s1
add r0.xyzw, r0.xyzw, -r1.xyzw
mad r0.xyzw, v3.zzzz, r0.xyzw, r1.xyzw
mul r0.xyzw, r0.xyzw, v2.xyzw
sample_indexable(texture2d)(float,float,float,float) r1.x, v0.xyxx, t2.wxyz, s0
mul o0.w, r0.w, r1.x
mov o0.xyz, r0.xyzx
ret
// Approximately 0 instruction slots used

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
