// Changes from the game's shader: o0, r2.xy, the gradient v in r1.y and the suffix flag in o3.w.
// Twin of DamageText-cf73c94cd003da41-vs.hlsl plus the italic slant; keep the two in sync.

#include ".\CompileOptions.h"

#define MAX_GLYPHS 144
// Max glyphs scanned each way; longer strings are left untouched.
#define MAX_STRING_SCAN 40
// IniParams x220, written by the ini.
#define INSTANCE_COUNT_SLOT 220

struct InstanceData {
    float4 uv_x;     // u for each vertex
    float4 uv_y;     // v for each vertex
    float4 quad_x;   // left, left, right, right
    float4 quad_y;   // top, bottom, bottom, top
    float4 fill;     // fill color
    float4 outline;  // outline color
    float3 position; // position anchor for the string
    float1 scale;    // glyph scale
};

struct Globals {
    float4 reserved[3];
    row_major float4x4 projection;
    float2 outline_width;
    float2 reserved_2;
};

// The original declares 14 float4s, but the game binds 2048 or 4096 bytes (18 or 36 glyphs).
// Sized for 144 glyphs; a smaller array cuts long strings in two.
// cbuffer cb2 : register(b2) { float4 cb2[14]; }
cbuffer cb2 : register(b2)
{
    InstanceData data[MAX_GLYPHS];
};
cbuffer cb1 : register(b1)
{ 
    float4 cb1[1];
};
cbuffer cb0 : register(b0)
{
    Globals globals;
};

// Game font atlas (vs-t100 = ps-t0 in the ini), sampled to recognize digits.
Texture2D<float4> FontAtlas : register(t100);

// 3Dmigoto declarations
#define cmp -
Texture1D<float4> IniParams : register(t120);

// SuffixGlyphs.dds cells, generated by tools/make_suffix_texture.py.
// Per cell: x = u0, y = u1, z = left edge from the pen (em), w = width (em).
static const float4 SUFFIX_CELLS[6] = {
    float4(0.000000, 0.040039, 0.02500, 0.25625),  // .
    float4(0.040039, 0.147461, -0.01250, 0.68750), // k
    float4(0.147461, 0.290039, -0.00625, 0.91250), // m
    float4(0.290039, 0.415039, -0.01250, 0.80000), // K
    float4(0.415039, 0.558594, -0.01250, 0.91875), // M
    float4(0.558594, 0.598633, 0.14375, 0.25625),  // !
};
// Cell band: TOP and BOTTOM in em from the baseline, v from 0 to SUFFIX_BAND_BOTTOM_V.
#define SUFFIX_BAND_TOP 0.8375
#define SUFFIX_BAND_BOTTOM 0.1250
#define SUFFIX_BAND_BOTTOM_V 0.6015625

// Synthetic italic of the special renderer (shear around the baseline).
#define ITALIC_SLANT 0.25

#define CELL_DOT 0
#define CELL_K 1
#define CELL_M 2
#define CELL_K_UPPER 3
#define CELL_M_UPPER 4
#define CELL_EXCLAMATION 5

// Game font metrics, generated by tools/make_digit_tables.py.
// Control box of the sheared outline: x min/max in 1/4 font units, y min/max in font units.
static const int4 DIGIT_CONTROL_BOX[10] = {
    int4(402, 3282, -50, 750), // 0
    int4(564, 2036, -60, 750), // 1
    int4(144, 2921, -40, 750), // 2
    int4(328, 2954, -50, 750), // 3
    int4(284, 3069, -60, 750), // 4
    int4(308, 3104, -50, 745), // 5
    int4(392, 2930, -50, 754), // 6
    int4(625, 3163, -50, 745), // 7
    int4(194, 3055, -50, 750), // 8
    int4(495, 2988, -50, 750), // 9
};
// Advances in font units (1000 per em), cells in SUFFIX_CELLS order.
static const int DIGIT_ADVANCE[10] = { 740, 395, 642, 662, 729, 663, 688, 586, 674, 637 };
static const int CELL_ADVANCE[6] = { 315, 634, 930, 730, 966, 501 };

// Sample points that tell apart digits with the same quad size (0/8 always, other pairs at some sizes).
// Spot coordinates: x from the quad's left edge, y from its bottom, both 0..1.
#define SPOT_COUNT 6
static const float2 SIGNATURE_SPOTS[SPOT_COUNT] = {
    float2(0.50, 0.55),
    float2(0.35, 0.30),
    float2(0.50, 0.90),
    float2(0.55, 0.45),
    float2(0.25, 0.40),
    float2(0.30, 0.55),
};
// Bit k = ink at spot k; spots with a 0 in DIGIT_RELIABLE_SPOTS are ignored for that digit.
static const uint DIGIT_SIGNATURE[10] = { 20, 11, 14, 5, 2, 37, 49, 7, 21, 12 };
static const uint DIGIT_RELIABLE_SPOTS[10] = { 31, 11, 63, 55, 7, 55, 61, 15, 23, 15 };

// Rounded half up, as the game does.
float pen_advance(int font_units, float font_size)
{
    return floor(font_units * font_size / 1000.0 + 0.5);
}

// Quads are the control box plus 1 px of padding per side.
float pen_to_quad_left(int digit, float font_size)
{
    return floor(DIGIT_CONTROL_BOX[digit].x * font_size / 4000.0) - 1.0;
}

float2 digit_quad_size(int digit, float font_size)
{
    int4 control_box = DIGIT_CONTROL_BOX[digit];
    return float2(ceil(control_box.y * font_size / 4000.0) - floor(control_box.x * font_size / 4000.0),
                  ceil(control_box.w * font_size / 1000.0) - floor(control_box.z * font_size / 1000.0)) + 2.0;
}

// Same string = same anchor position and scale.
bool same_anchor(int neighbor_glyph, int glyph)
{
    return !(any(abs(data[neighbor_glyph].position - data[glyph].position) > 1e-4) ||
             abs(data[neighbor_glyph].scale - data[glyph].scale) > 1e-4);
}

// Returns false if the scan hits MAX_STRING_SCAN on either side.
bool find_string(int glyph, int draw_start, int draw_end, out int string_start, out int string_end)
{
    // Stop when x stops increasing: leftover copies of a number restart from the left.
    string_start = glyph;
    [loop] while (string_start > draw_start && glyph - string_start < MAX_STRING_SCAN) {
        if (!same_anchor(string_start - 1, glyph) ||
            data[string_start - 1].quad_x[0] >= data[string_start].quad_x[0])
            break;
        string_start--;
    }
    string_end = glyph + 1;
    [loop] while (string_end < draw_end && string_end - 1 - glyph < MAX_STRING_SCAN) {
        if (!same_anchor(string_end, glyph) ||
            data[string_end].quad_x[0] <= data[string_end - 1].quad_x[0])
            break;
        string_end++;
    }
    return glyph - string_start < MAX_STRING_SCAN && string_end - 1 - glyph < MAX_STRING_SCAN;
}

uint ink_signature(int glyph)
{
    uint atlas_width, atlas_height;
    FontAtlas.GetDimensions(atlas_width, atlas_height);
    // Interpolated from the corner uvs to handle glyphs that are packed rotated.
    float2 top_left = float2(data[glyph].uv_x[0], data[glyph].uv_y[0]);
    float2 bottom_left = float2(data[glyph].uv_x[1], data[glyph].uv_y[1]);
    float2 bottom_right = float2(data[glyph].uv_x[2], data[glyph].uv_y[2]);
    float2 top_right = float2(data[glyph].uv_x[3], data[glyph].uv_y[3]);
    uint signature = 0;
    [unroll] for (int spot = 0; spot < SPOT_COUNT; spot++) {
        float2 spot_bottom = lerp(bottom_left, bottom_right, SIGNATURE_SPOTS[spot].x);
        float2 spot_top = lerp(top_left, top_right, SIGNATURE_SPOTS[spot].x);
        float2 spot_uv = lerp(spot_bottom, spot_top, SIGNATURE_SPOTS[spot].y);
        if (FontAtlas.Load(int3((int2)(spot_uv * float2(atlas_width, atlas_height)), 0)).w > 0.5)
            signature |= 1u << spot;
    }
    return signature;
}

int recognize_digit(int glyph, float2 digit_quad_sizes[10], out float misfit)
{
    float2 quad_size = float2(data[glyph].quad_x[2] - data[glyph].quad_x[0],
                              data[glyph].quad_y[0] - data[glyph].quad_y[1]);
    uint glyph_signature = ink_signature(glyph);
    int best_digit = 0;
    misfit = 1e9;
    [unroll] for (int digit = 0; digit < 10; digit++) {
        float2 size_difference = abs(digit_quad_sizes[digit] - quad_size);
        // 8 per pixel of size error, 1 per mismatching spot: the size always wins.
        float score = (size_difference.x + size_difference.y) * 8.0 +
                      countbits((glyph_signature ^ DIGIT_SIGNATURE[digit]) & DIGIT_RELIABLE_SPOTS[digit]);
        if (score < misfit) {
            misfit = score;
            best_digit = digit;
        }
    }
    return best_digit;
}

// Tries the sizes around the guess; the right one fits every digit and centers the run.
float match_font_size(int string_start, int string_length, int integer_digits, float average_height,
                      out int first_digit, out int decimal_digit)
{
    // Quad height is about 0.8 * size + 2.8, so the guess is off by 1 at most.
    float font_size_guess = (average_height - 2.8) / 0.8;
    float nearest_size = round(font_size_guess);
    float guess_side = (font_size_guess >= nearest_size) ? 1.0 : -1.0;
    float font_size = nearest_size;
    first_digit = 0;
    decimal_digit = 0;
    float best_score = 1e9;
    [loop] for (int attempt = 0; attempt < 3; attempt++) {
        // Order: nearest, neighbor on the guess's side, other neighbor.
        float candidate_size = nearest_size;
        if (attempt == 1)
            candidate_size += guess_side;
        if (attempt == 2)
            candidate_size -= guess_side;
        float2 digit_quad_sizes[10];
        [unroll] for (int digit = 0; digit < 10; digit++)
            digit_quad_sizes[digit] = digit_quad_size(digit, candidate_size);
        float total_advance = 0.0;
        float total_misfit = 0.0;
        int candidate_first_digit = 0;
        int candidate_decimal_digit = 0;
        [loop] for (int i = 0; i < string_length; i++) {
            float digit_misfit;
            int recognized_digit = recognize_digit(string_start + i, digit_quad_sizes, digit_misfit);
            if (i == 0)
                candidate_first_digit = recognized_digit;
            if (i == integer_digits)
                candidate_decimal_digit = recognized_digit;
            total_advance += pen_advance(DIGIT_ADVANCE[recognized_digit], candidate_size);
            total_misfit += digit_misfit;
        }
        // The game starts the pen at -total_advance / 2.
        float pen_start = data[string_start].quad_x[0] - pen_to_quad_left(candidate_first_digit, candidate_size);
        bool is_centered = abs(total_advance + 2.0 * pen_start) <= 0.25;
        float score = (is_centered ? 0.0 : 1000.0) + total_misfit + abs(candidate_size - font_size_guess);
        if (score < best_score) {
            best_score = score;
            font_size = candidate_size;
            first_digit = candidate_first_digit;
            decimal_digit = candidate_decimal_digit;
        }
        // Exact match; no need to try the other sizes.
        if (is_centered && total_misfit == 0.0)
            break;
    }
    return font_size;
}

// Per-corner uvs because some glyphs are packed rotated.
void copy_digit(int source_glyph, int corner, float shift_x, out float2 uv, out float2 quad)
{
    uv = float2(data[source_glyph].uv_x[corner], data[source_glyph].uv_y[corner]);
    quad = float2(data[source_glyph].quad_x[corner] + shift_x, data[source_glyph].quad_y[corner]);
}

void place_suffix_cell(int cell, float pen, float baseline, float font_size, int corner, out float2 uv, out float2 quad)
{
    bool is_right = corner >= 2;
    bool is_bottom = corner == 1 || corner == 2;
    uv = float2(is_right ? SUFFIX_CELLS[cell].y : SUFFIX_CELLS[cell].x, is_bottom ? SUFFIX_BAND_BOTTOM_V : 0.0);
    float left_edge = pen + SUFFIX_CELLS[cell].z * font_size;
    quad.y = is_bottom ? baseline - SUFFIX_BAND_BOTTOM * font_size : baseline + SUFFIX_BAND_TOP * font_size;
    // Same shear as the digits, around the baseline.
    quad.x = (is_right ? left_edge + SUFFIX_CELLS[cell].w * font_size : left_edge) + ITALIC_SLANT * (quad.y - baseline);
}

// Returns true if the vertex now belongs to a suffix cell (PS flag).
bool compact_number(int glyph, int vertex, inout float2 uv, inout float2 quad, inout float ramp)
{
    // The draw reads glyphs cb1[0].x to cb1[0].x + instance_count - 1.
    // The rest of cb2 holds leftovers from other draws.
    int instance_count = (int)IniParams[INSTANCE_COUNT_SLOT].x;
    if (instance_count <= 0 || instance_count > MAX_GLYPHS)
        return false;
    int draw_start = asint(cb1[0].x);

    int string_start, string_end;
    if (!find_string(glyph, draw_start, draw_start + instance_count, string_start, string_end))
        return false;
    int string_length = string_end - string_start;
    if (string_length < MIN_DIGITS)
        return false;

    float top_min = 1e9;
    float top_max = -1e9;
    float top_sum = 0.0;
    float bottom_sum = 0.0;
    [loop] for (int string_glyph = string_start; string_glyph < string_end; string_glyph++) {
        float quad_top = data[string_glyph].quad_y[0];
        top_min = min(top_min, quad_top);
        top_max = max(top_max, quad_top);
        top_sum += quad_top;
        bottom_sum += data[string_glyph].quad_y[1];
    }
    // Digits share one quad top; letters (Melt, Vaporize) don't.
    bool is_number = top_max - top_min <= TOP_TOLERANCE;
    if (!is_number)
        return false;
    float average_bottom = bottom_sum / (float)string_length;
    float average_height = top_sum / (float)string_length - average_bottom;
    // Crits differ only in font size; color and scale are the same.
    bool is_crit = average_height > CRIT_HEIGHT;

    // Layout: integer digits, [. decimal], suffix, [!].
    bool is_millions = string_length >= 7;
    int integer_digits = is_millions ? string_length - 6 : string_length - 3;
    int suffix_cell = is_millions ? CELL_M : CELL_K;
    if (CRITICAL_UPPERCASE && is_crit)
        suffix_cell = is_millions ? CELL_M_UPPER : CELL_K_UPPER;
    bool show_decimal = integer_digits <= SHOW_DECIMALS;
    bool show_exclamation = CRITICAL_INDICATOR && is_crit;
    int short_length = integer_digits + (show_decimal ? 2 : 0) + 1 + (show_exclamation ? 1 : 0);
    // No spare instance for the !; drop the decimal.
    if (short_length > string_length) {
        show_decimal = false;
        short_length -= 2;
    }
    int this_position = glyph - string_start;
    // Unused glyphs collapse to a point.
    if (this_position >= short_length) {
        quad = 0.0;
        return false;
    }

    // Rebuild the game's pen positions from the quads and the font metrics.
    int first_digit, decimal_digit;
    float font_size = match_font_size(string_start, string_length, integer_digits, average_height, first_digit, decimal_digit);
    float first_pen = data[string_start].quad_x[0] - pen_to_quad_left(first_digit, font_size);
    float decimal_pen = data[string_start + integer_digits].quad_x[0] - pen_to_quad_left(decimal_digit, font_size);
    float baseline = data[string_start + integer_digits].quad_y[1] - floor(DIGIT_CONTROL_BOX[decimal_digit].z * font_size / 1000.0) + 1.0;
    float dot_advance = pen_advance(CELL_ADVANCE[CELL_DOT], font_size);
    float suffix_pen = decimal_pen + (show_decimal ? dot_advance + pen_advance(DIGIT_ADVANCE[decimal_digit], font_size) : 0.0);
    float suffix_advance = pen_advance(CELL_ADVANCE[suffix_cell], font_size);
    float run_end = suffix_pen + suffix_advance + (show_exclamation ? pen_advance(CELL_ADVANCE[CELL_EXCLAMATION], font_size) : 0.0);
    // Recenter on the anchor, as the game does.
    float center_shift = -(run_end - first_pen) * 0.5 - first_pen;

    int corner = clamp(vertex, 0, 3);
    if (this_position < integer_digits) {
        copy_digit(glyph, corner, center_shift, uv, quad);
        return false;
    }
    if (show_decimal && this_position == integer_digits + 1) {
        // Decimal shifted right by the dot's advance.
        copy_digit(string_start + integer_digits, corner, center_shift + dot_advance, uv, quad);
        return false;
    }
    int placed_cell = suffix_cell;
    float cell_pen = suffix_pen;
    if (show_decimal && this_position == integer_digits) {
        // Dot at the decimal's pen.
        placed_cell = CELL_DOT;
        cell_pen = decimal_pen;
    } else if (show_exclamation && this_position == short_length - 1) {
        placed_cell = CELL_EXCLAMATION;
        cell_pen = suffix_pen + suffix_advance;
    }
    place_suffix_cell(placed_cell, cell_pen + center_shift, baseline, font_size, corner, uv, quad);
    // Gradient v in digit box space; the PS saturates the band's overshoot.
    ramp = (quad.y - average_bottom) / average_height;
    return true;
}

void main(
    float4 v0 : POSITION0,
    uint v1 : SV_InstanceID0,
    out float2 o0 : TEXCOORD0,
    out float4 o1 : SV_POSITION0,
    out float4 o2 : COLOR0,
    out float4 o3 : TEXCOORD1,
    out uint o4 : SV_InstanceID0)
{
    const float4 icb[] = {{ 1, 0, 0, 0},
                          { 0, 1, 0, 0},
                          { 0, 0, 1, 0},
                          { 0, 0, 0, 1}};
    float4 r0,r1,r2,r3;
    uint4 bitmask, uiDest;
    float4 fDest;

    r0.x = (int)v1.x + asint(cb1[0].x);
    r0.y = (int)v0.x;
    // Gradient uv: x = 1 on the right corners, y = 1 on the top ones.
    r1.xyz = cmp((int3)r0.yyy == int3(2,3,0));
    r0.zw = (int2)r1.yy | (int2)r1.xz;
    // 0x3f800000 = 1.0f; without asfloat it compiles to 1065353216.0.
    // r1.xy = (int2)r0.zw & int2(0x3f800000,0x3f800000);
    r1.xy = asfloat((int2)r0.zw & int2(0x3f800000,0x3f800000));
    // No * 7: data[] is indexed per glyph.
    // r0.x = (int)r0.x * 7;
    int glyph = r0.x;
    // Quad corner 0..3, same order as quad_x and quad_y.
    int vertex = r0.y;
    // A dot() with an identity row only selects a component; index it directly.
    // o0.x = dot(cb2[r0.x+0].xyzw, icb[r0.y+0].xyzw);
    // o0.y = dot(cb2[r0.x+1].xyzw, icb[r0.y+0].xyzw);
    // r2.x = dot(cb2[r0.x+2].xyzw, icb[r0.y+0].xyzw);
    // r2.y = dot(cb2[r0.x+3].xyzw, icb[r0.y+0].xyzw);
    o0.x = data[glyph].uv_x[vertex];
    o0.y = data[glyph].uv_y[vertex];
    r2.x = data[glyph].quad_x[vertex];
    r2.y = data[glyph].quad_y[vertex];

    // 1 = the PS samples SuffixGlyphs instead of the atlas.
    float suffix_flag = compact_number(glyph, vertex, o0, r2.xy, r1.y) ? 1.0 : 0.0;

    // r0.y = cmp(0 != v0.y);
    bool has_outline = v0.y != 0;

    if (has_outline) {
        // Outline = 4 copies offset diagonally by outline_width; v0.z picks the copy.
        o2.xyzw = data[glyph].outline.rgba * data[glyph].fill.a;
        r0.y = (int)v0.z;
        r0.z = (int)r0.y & 1;
        r0.y = (uint)r0.y >> 1;
        r3.xy = (int2)r0.zy;
        r0.yz = r3.xy * float2(2,2) + float2(-1,-1);
        r2.xy = r0.yz * globals.outline_width + r2.xy;
        r1.z = 1;
    } else {
        o2.xyzw = data[glyph].fill;
        r1.z = 0;
    }
    r2.xy = data[glyph].scale * r2.xy;
    r2.z = 0;
    r0.xyz = data[glyph].position + r2.xyz;
    // r2.xyzw = cb0[4].xyzw * r0.yyyy;
    // r2.xyzw = cb0[3].xyzw * r0.xxxx + r2.xyzw;
    // r0.xyzw = cb0[5].xyzw * r0.zzzz + r2.xyzw;
    // o1.xyzw = cb0[6].xyzw + r0.xyzw;
    o1.xyzw = globals.projection[0] * r0.x + globals.projection[1] * r0.y + globals.projection[2] * r0.z + globals.projection[3];
    // Flag in w: TEXCOORD1.xyz holds the gradient.
    // r1.w = 0;
    r1.w = suffix_flag;
    o3.xyzw = r1.xyzw;
    o4.x = v1.x;
    return;
}

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.3.16 on Mon Sep 21 12:28:11 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz
// SV_InstanceID            0   x           1   INSTID    uint   x
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy
// SV_POSITION              0   xyzw        1      POS   float   xyzw
// COLOR                    0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
// SV_InstanceID            0   x           4     NONE    uint   x
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000} }
dcl_constantbuffer CB0[8], immediateIndexed
dcl_constantbuffer CB1[1], immediateIndexed
dcl_constantbuffer CB2[14], dynamicIndexed
dcl_input v0.xyz
dcl_input_sgv v1.x, instance_id
dcl_output o0.xy
dcl_output_siv o1.xyzw, position
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.x
dcl_temps 4
iadd r0.x, v1.x, cb1[0].x
ftoi r0.y, v0.x
ieq r1.xyz, r0.yyyy, l(2, 3, 0, 0)
or r0.zw, r1.yyyy, r1.xxxz
and r1.xy, r0.zwzz, l(0x3f800000, 0x3f800000, 0, 0)
imul null, r0.x, r0.x, l(7)
dp4 o0.x, cb2[r0.x + 0].xyzw, icb[r0.y + 0].xyzw
dp4 o0.y, cb2[r0.x + 1].xyzw, icb[r0.y + 0].xyzw
dp4 r2.x, cb2[r0.x + 2].xyzw, icb[r0.y + 0].xyzw
dp4 r2.y, cb2[r0.x + 3].xyzw, icb[r0.y + 0].xyzw
ne r0.y, l(0.000000, 0.000000, 0.000000, 0.000000), v0.y
if_nz r0.y
  mul o2.xyzw, cb2[r0.x + 4].wwww, cb2[r0.x + 5].xyzw
  ftoi r0.y, v0.z
  and r0.z, r0.y, l(1)
  ishr r0.y, r0.y, l(1)
  itof r3.xy, r0.zyzz
  mad r0.yz, r3.xxyx, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
  mad r2.xy, r0.yzyy, cb0[7].xyxx, r2.xyxx
  mov r1.z, l(1.000000)
else
  mov o2.xyzw, cb2[r0.x + 4].xyzw
  mov r1.z, l(0)
endif
mul r2.xy, r2.xyxx, cb2[r0.x + 6].wwww
mov r2.z, l(0)
add r0.xyz, r2.xyzx, cb2[r0.x + 6].xyzx
mul r2.xyzw, r0.yyyy, cb0[4].xyzw
mad r2.xyzw, cb0[3].xyzw, r0.xxxx, r2.xyzw
mad r0.xyzw, cb0[5].xyzw, r0.zzzz, r2.xyzw
add o1.xyzw, r0.xyzw, cb0[6].xyzw
mov r1.w, l(0)
mov o3.xyzw, r1.xyzw
mov o4.x, v1.x
ret
// Approximately 0 instruction slots used

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
